
- alias: "switch TV av"
  hide_entity: false
  trigger:
  - event_data:
      entity_id: zwave.zwaveme_zme_wallcs_secure_wall_controller
      scene_id: 2
    event_type: zwave.scene_activated
    platform: event

  action:
  - service: media_player.turn_off
    entity_id: media_player.sony_bravia_tv



- alias: "switch lys stue på"
  hide_entity: false
  trigger:
  - event_data:
      entity_id: zwave.zwaveme_zme_wallcs_secure_wall_controller
      scene_id: 5
    event_type: zwave.scene_activated
    platform: event

  action:
  - service: homeassistant.turn_on
    entity_id: group.stue_lys

- alias: "switch lys stue av"
  hide_entity: false
  trigger:
  - event_data:
      entity_id: zwave.zwaveme_zme_wallcs_secure_wall_controller
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event

  action:
  - service: homeassistant.turn_off
    entity_id: group.stue_lys




- alias: "scheduled lys stue på"
  hide_entity: false
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 5.0
  - platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state.attributes.elevation }}"
    below: 15.0
  
  condition:
    condition: or
    conditions:
    - condition: numeric_state
      entity_id: sun.sun
      value_template: "{{ state.attributes.elevation }}"
      below: 10.0
    - condition: and
      conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: "{{ state.attributes.elevation }}"
        below: 15.0
      - condition: numeric_state
        entity_id: sensor.yr_cloudiness
        value_template: "{{ float(state.state) }}"
        above: 50.0
  action:
  - service: homeassistant.turn_on
    entity_id: group.stue_lys
 
- alias: "scheduled lys stue av weekend"
  hide_entity: false
  trigger:
   - platform: time
     at: '00:50'

  condition:
  - condition: time
    weekday:
      - sat
      - sun
 

  action:
   - service: homeassistant.turn_off
     entity_id: group.stue_lys 


- alias: "scheduled lys stue av ukedager"
  hide_entity: false
  trigger:
   - platform: time
     at: '23:30'

  condition:
  - condition: time
    weekday:
      - sun
      - mon
      - tue
      - wed
      - thu

  action:
   - service: homeassistant.turn_off
     entity_id: group.stue_lys

- alias: "stereo loft av"
  hide_entity: false
  trigger: 
   - platform: time
     at: '00:10'

  action:
     service: homeassistant.turn_off
     entity_id: switch.fibaro_system_fgwpef_wall_plug_gen5_switch
